version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:5000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Add other environment variables as needed, e.g.:
      # - MONGO_URI=${MONGO_URI}
      # - JWT_SECRET=${JWT_SECRET}

networks:
  default:
    name: image-generator-network
